### ISSUE TITLE
[W7-Kaggle_competition] Antonio Pita

### ISSUE THREAD

**Issue by Antoniopita95** [Ironhack-Data-Madrid-Marzo-2021/W7-Kaggle_competition#12]
https://github.com/Antoniopita95/W7-Diamond_competition

**Comment by AnaAGG** [comment]
# 💎 Kaggle competition 💎

Holaaaaa Antonio 🙋‍♀️🔥 y por fin el último proyecto! 

Vamos a empezar con un resumen de la estructura de un modelo de *machine learning*, cual es el *workflow y los objetivos que perseguimos al realizar este tipo de análisis. 

El **objetivo** ---> elegir el mejor modelo que prediga en base a unos datos que le pasemos. 

    ¿Cómo podemos conseguir esto??
Aunque no existe una receta perfecta, hay una serie de variables que nosotros podemos ir controlando y evaluando a lo largo de todo el proceso que nos pueden ayudar a conseguir nuestros objetivos: 

1. Pre-procesamiento de los datos, es la parte más importante de un modelo de *machine learning*, es lo que puede hacer que nuestros modelos sean más precisos. 
  
    - Limpiar los datos

    - Evaluar autocorrelación entre las variables predictoras
  
    - Convertir las variables categóricas
  
       - Hot-encodoing 
     
       - Get dummies
  
   - Qué parámetros/variables vamos a usar en nuestro modelo.

- Investigar el modelo que será mejor para nuestros datos.

- Entrenar el modelo (*train-test split*).
  - Probar distintos modelos
  
  - Grid search: para las permutaciones de los parámetros

- Evaluación de nuestro modelo. 
  - Cross-validation: para garantizar el corte de los datos

---
---
En concreto en tu proyecto: 

### Readme

En general está bien, aunque podrías haber detallado algo mejor cuales fueron los pasos que seguiste para llegar a tu modelo. ¿Qué tecnologías usaste? ¿Hiciste algún tipo de limpieza de datos? ¿Qué hiciste con las variables categóricas?

### Estructura del repo

Suuper bien, no se te ha colado ningún archivo raro, ni ningún archivo temporal 👏🏽.  Lo tienes todo en carpetas y super bien organizado, buen trabajo! 

### Sintaxis de código

- Haces el `get_dummies` de todas las variables categóricas, pero recuerda que tenemos el `hot encoding` [docu](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) que nos ayuda en aquellos casos tenemos variables tienen clasificaciones (van de peor a mejor, como pasaba con el color)

- Recuerda, los jupyters bien documentados siempre ayudan, sobre todo para alguien que no sepa de que va tu proyecto. Tener siempre una especie de guía que estas haciendo y por qué

- Has probado distintos modelos lo cual esta genial, en algunos casos usaste el `GridSearch` lo cual le aporta mucho valor a tus resultados, pero recuerda que usando esta herramienta puedes combinar disntintos tipos de modelos y parámetros! 
  
- Para el futuro, por si te animas, puedes usar H20: https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html. 

Buen trabajo Antonio!! 🔥

![image](https://user-images.githubusercontent.com/75084991/120190108-6f76ea80-c218-11eb-843f-4b510d9fa14d.png)
